name: workflow_release
on:
  workflow_dispatch:
  
jobs:
    build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - uses: nowsprinting/check-version-format-action@v3
         id: version
         with:
           prefix: 'v'
        
       - name: Create release
         env:
           GITHUB_TOKEN: ${{ secrets.TOKEN_PULLREQ }}
         run: |
           gh release create "${{steps.version.outputs.full}}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="Release ${{steps.version.outputs.full_without_prefix}}" \
            --generate-notes \
            ${{ steps.version.outputs.is_stable != 'true' && '--prerelease' || '' }}
         shell: bash
